import "../globals.css";

export default function Terms() {
  return (
    <div style={styles.wrapper}>
      <nav style={styles.nav}>
        <a href="/" style={styles.logo}>
          <span style={{ fontSize: 22 }}>📬</span>
          <span style={styles.logoText}>Email Brief</span>
        </a>
      </nav>

      <main style={styles.main}>
        <h1 style={styles.title}>Terms of Service</h1>
        <p style={styles.updated}>Last updated: April 2026</p>

        <section style={styles.section}>
          <h2 style={styles.h2}>Acceptance of Terms</h2>
          <p style={styles.p}>
            By using Email Brief, you agree to these Terms of Service. If you do
            not agree, please do not use the service.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>Description of Service</h2>
          <p style={styles.p}>
            Email Brief is a free, open-source tool that connects to your Gmail
            account (with your permission) to read your recent emails, generate
            AI-powered summaries, and prioritize your inbox. The service is
            provided &quot;as is&quot; without warranties of any kind.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>Your Gmail Data</h2>
          <p style={styles.p}>
            Email Brief accesses your Gmail in <strong>read-only mode</strong>.
            We cannot and will not send, delete, or modify your emails. Your
            email content is processed for summarization purposes only and is not
            stored on our servers. See our{" "}
            <a href="/privacy">Privacy Policy</a> for full details.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>User Responsibilities</h2>
          <ul style={styles.ul}>
            <li>
              You are responsible for maintaining the security of your device and
              any tokens stored locally.
            </li>
            <li>
              You must have the authority to grant read access to the Gmail
              account you connect.
            </li>
            <li>
              You agree not to use Email Brief for any unlawful purpose.
            </li>
          </ul>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>AI-Generated Content</h2>
          <p style={styles.p}>
            Email summaries and priority scores are generated by AI (Google
            Gemini). These are approximations and may not be perfectly accurate.
            Always refer to the original email for critical decisions. Email Brief
            is not responsible for actions taken based on AI-generated summaries.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>Limitation of Liability</h2>
          <p style={styles.p}>
            Email Brief is provided free of charge and without warranty. To the
            maximum extent permitted by law, the developers of Email Brief shall
            not be liable for any indirect, incidental, or consequential damages
            arising from your use of the service.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>Termination</h2>
          <p style={styles.p}>
            You can stop using Email Brief at any time by revoking access at{" "}
            <a href="https://myaccount.google.com/permissions">
              Google Account Permissions
            </a>{" "}
            and deleting the local application data.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>Changes to Terms</h2>
          <p style={styles.p}>
            We may update these terms from time to time. Continued use of Email
            Brief after changes constitutes acceptance of the updated terms.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.h2}>Contact</h2>
          <p style={styles.p}>
            For questions about these terms, contact{" "}
            <a href="mailto:support@emailbrief.app">support@emailbrief.app</a>.
          </p>
        </section>
      </main>

      <footer style={styles.footer}>
        <p>
          © {new Date().getFullYear()} Email Brief —{" "}
          <a href="/">Home</a> · <a href="/privacy">Privacy</a>
        </p>
      </footer>
    </div>
  );
}

const styles: Record<string, React.CSSProperties> = {
  wrapper: { minHeight: "100vh", display: "flex", flexDirection: "column" },
  nav: {
    borderBottom: "1px solid #e5e7eb",
    background: "#fff",
    padding: "14px 24px",
  },
  logo: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    textDecoration: "none",
    color: "#111827",
  },
  logoText: { fontSize: 18, fontWeight: 700 },
  main: {
    flex: 1,
    maxWidth: 700,
    margin: "0 auto",
    padding: "48px 24px",
  },
  title: { fontSize: 32, fontWeight: 700, marginBottom: 4 },
  updated: { fontSize: 14, color: "#9ca3af", marginBottom: 36 },
  section: { marginBottom: 28 },
  h2: { fontSize: 18, fontWeight: 600, marginBottom: 8 },
  p: { fontSize: 15, color: "#4b5563", lineHeight: 1.7 },
  ul: {
    fontSize: 15,
    color: "#4b5563",
    lineHeight: 1.7,
    paddingLeft: 24,
  },
  footer: {
    borderTop: "1px solid #e5e7eb",
    padding: "20px 24px",
    textAlign: "center",
    fontSize: 13,
    color: "#9ca3af",
  },
};
